import streamlit as st
import requests
import os 
BACKEND_URL = os.getenv("BACKEND_URL", "http://127.0.0.1:8000")

# 1. Page Configuration
st.set_page_config(page_title="NB Media Agent Dashboard", page_icon="", layout="centered")

st.title(" NB Media AI Content Agent")
st.markdown("Automated LinkedIn growth engine. Mimics Nikit Bassi's writing framework.")

st.divider()

# 2. Control Panel
st.subheader(" Agent Control Panel")
st.write("Trigger the web-scraping and post-generation pipeline on demand.")

if st.button(" Run Auto-Research Pipeline Now", use_container_width=True):
    with st.spinner("Agent is actively scraping the web and generating posts... (Check terminal for live logs)"):
        try:
            # Hit your FastAPI backend
            response = requests.post("http://127.0.0.1:8000/api/v1/trigger-now")
            
            if response.status_code == 200:
                st.success(" Pipeline executed successfully! The generated posts have been printed to your backend terminal.")
            else:
                st.error(f" Backend returned an error: {response.status_code}")
        except Exception as e:
            st.error(f" Failed to connect to the backend. Is your FastAPI server running? Error: {e}")

st.divider()
# 3. Database Viewer (The Content Vault)
st.subheader(" Content Vault (Generated Posts)")
st.write("Review and copy posts generated by the agent.")

if st.button(" Refresh Database"):
    # This just triggers a re-render
    pass

try:
    db_response = requests.get("http://127.0.0.1:8000/api/v1/posts")
    if db_response.status_code == 200:
        posts = db_response.json()
        
        if not posts:
            st.info("No posts generated yet. Run the pipeline above!")
        else:
            for post in posts:
                # Create a neat dropdown for every post
                with st.expander(f" {post['topic_title']} ({post['created_at'][:10]})"):
                    st.caption(f"Source: {post['source_url']}")
                    st.markdown("**The Hook:**")
                    st.info(post['hook'])
                    
                    st.markdown("**Final Post Copy:**")
                    st.code(post['full_post_body'], language="text")
                    
                    st.markdown("**Visual Asset Idea:**")
                    st.success(post['image_concept'])
                    
                    st.button(" Copy for LinkedIn", key=post['id'], help="In production, this would trigger an auto-publish API.")
except Exception as e:
    st.error("Could not connect to database. Ensure FastAPI is running.")